language: php

php:
	- 8.0
    - 8.1

install:
    - travis_retry composer install --no-progress --prefer-dist

script:
    - vendor/bin/tester -p php -s tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

dist: bionic

cache:
    directories:
        - $HOME/.composer/cache
